import 'pharmacy_models.dart';

/// الكتالوج الافتراضي لباقات المكملات (35 باقة).
class PharmacyCatalogBundles {
  PharmacyCatalogBundles._();

  static const _img = [
    'https://images.unsplash.com/photo-1550572017-edd951aa8f72?w=500&q=80',
    'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=500&q=80',
    'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=500&q=80',
    'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=500&q=80',
    'https://images.unsplash.com/photo-1576602976047-174e57a47881?w=500&q=80',
  ];

  static String _sub(List<String> items) => items.take(4).join(' · ');

  static PharmacyBundle _b({
    required String id,
    required String title,
    required String icon,
    required List<String> supplements,
    List<String> optional = const [],
    String note = '',
    int imageIndex = 0,
    bool isPopular = false,
  }) {
    return PharmacyBundle(
      id: id,
      title: title,
      subtitle: _sub(supplements),
      price: 0,
      oldPrice: 0,
      icon: icon,
      imageUrl: _img[imageIndex % _img.length],
      isPopular: isPopular,
      isVisible: true,
      supplements: supplements,
      optionalSupplements: optional,
      note: note,
    );
  }

  /// قائمة موحدة لاختيار «باقتك بنفسك».
  static const customPickerOptions = <String>[
    'Multivitamin & Minerals',
    'Men\'s Multivitamin',
    'Women\'s Multivitamin',
    'Multivitamin 50+',
    'Men\'s Multivitamin 50+',
    'Women\'s Multivitamin 50+',
    'Children\'s Multivitamin',
    'Postnatal Multivitamin',
    'Vitamin D3',
    'Vitamin C',
    'Vitamin B Complex',
    'Vitamin B1',
    'Vitamin B2',
    'Vitamin B3',
    'Vitamin B5',
    'Vitamin B6',
    'Vitamin B12',
    'Biotin (B7)',
    'Folate (B9)',
    'Folic Acid',
    'Omega-3 (EPA + DHA)',
    'Fish Oil / Omega-3',
    'Algal DHA/EPA',
    'Zinc',
    'Magnesium',
    'Magnesium Citrate',
    'Magnesium Glycinate',
    'Magnesium Oxide',
    'Calcium',
    'Iron',
    'Iodine',
    'Vitamin K2',
    'Vitamin E',
    'Copper',
    'Lutein',
    'Zeaxanthin',
    'Collagen Peptides',
    'Hydrolyzed Collagen',
    'Protein',
    'Whey Protein',
    'Creatine Monohydrate',
    'Electrolytes',
    'Glucosamine',
    'Chondroitin',
    'MSM',
    'Coenzyme Q10 (CoQ10)',
    'Cyanocobalamin',
    'Methylcobalamin',
  ];

  static final List<PharmacyBundle> all = [
    _b(
      id: 'daily_wellness',
      title: 'باقة الصحة اليومية',
      icon: '☀️',
      supplements: const [
        'Multivitamin & Minerals',
        'Vitamin D3',
        'Omega-3 (EPA + DHA)',
      ],
      imageIndex: 0,
      isPopular: true,
    ),
    _b(
      id: 'immune',
      title: 'باقة دعم المناعة',
      icon: '🛡️',
      supplements: const ['Vitamin D3', 'Vitamin C', 'Zinc'],
      imageIndex: 1,
      isPopular: true,
    ),
    _b(
      id: 'energy',
      title: 'باقة الطاقة والنشاط',
      icon: '⚡',
      supplements: const [
        'Vitamin B Complex',
        'Vitamin B12',
        'Magnesium',
        'Multivitamin',
      ],
      imageIndex: 2,
      isPopular: true,
    ),
    _b(
      id: 'mens_daily',
      title: 'باقة الرجل اليومية',
      icon: '🧔',
      supplements: const [
        'Men\'s Multivitamin',
        'Vitamin D3',
        'Zinc',
        'Magnesium',
        'Omega-3',
      ],
      imageIndex: 3,
    ),
    _b(
      id: 'womens_daily',
      title: 'باقة المرأة اليومية',
      icon: '💐',
      supplements: const [
        'Women\'s Multivitamin',
        'Vitamin D3',
        'Magnesium',
        'Omega-3',
      ],
      optional: const ['Iron', 'Folic Acid'],
      note: 'اختياري حسب تقييم الصيدلي/الفحوصات',
      imageIndex: 4,
      isPopular: true,
    ),
    _b(
      id: 'bones',
      title: 'باقة العظام',
      icon: '🦴',
      supplements: const ['Calcium', 'Vitamin D3', 'Magnesium'],
      optional: const ['Vitamin K2'],
      note: 'اختياري حسب المنتج والحاجة',
      imageIndex: 0,
      isPopular: true,
    ),
    _b(
      id: 'muscle',
      title: 'باقة العضلات',
      icon: '💪',
      supplements: const ['Magnesium', 'Vitamin D3'],
      optional: const ['Protein', 'Creatine Monohydrate'],
      note: 'للرياضيين حسب الحاجة',
      imageIndex: 1,
    ),
    _b(
      id: 'sports',
      title: 'باقة الرياضي',
      icon: '🏃',
      supplements: const [
        'Creatine Monohydrate',
        'Protein',
        'Electrolytes',
        'Magnesium',
      ],
      optional: const ['Omega-3', 'Multivitamin'],
      imageIndex: 2,
    ),
    _b(
      id: 'muscle_building',
      title: 'باقة بناء العضلات',
      icon: '🏋️',
      supplements: const [
        'Whey Protein / Protein Supplement',
        'Creatine Monohydrate',
      ],
      optional: const ['Electrolytes', 'Magnesium'],
      imageIndex: 3,
    ),
    _b(
      id: 'sports_recovery',
      title: 'باقة الاستشفاء الرياضي',
      icon: '🔄',
      supplements: const ['Protein', 'Electrolytes', 'Magnesium'],
      optional: const ['Omega-3'],
      imageIndex: 4,
    ),
    _b(
      id: 'hair',
      title: 'باقة الشعر',
      icon: '💇',
      supplements: const ['Biotin', 'Zinc'],
      optional: const ['Vitamin D', 'Iron', 'Collagen'],
      note: 'حسب الحاجة/التحاليل',
      imageIndex: 0,
    ),
    _b(
      id: 'skin_beauty',
      title: 'باقة البشرة والجمال',
      icon: '✨',
      supplements: const ['Collagen Peptides', 'Vitamin C'],
      optional: const ['Zinc', 'Biotin'],
      imageIndex: 1,
    ),
    _b(
      id: 'hair_skin_nails',
      title: 'باقة الشعر والبشرة والأظافر',
      icon: '💅',
      supplements: const ['Biotin', 'Zinc', 'Vitamin C', 'Collagen'],
      imageIndex: 2,
    ),
    _b(
      id: 'heart',
      title: 'باقة صحة القلب العامة',
      icon: '❤️',
      supplements: const ['Omega-3 (EPA + DHA)'],
      optional: const ['Magnesium', 'Coenzyme Q10 (CoQ10)'],
      note: 'اختياري حسب تقييم الصيدلي',
      imageIndex: 3,
    ),
    _b(
      id: 'nervous',
      title: 'باقة دعم الجهاز العصبي',
      icon: '🧠',
      supplements: const [
        'Vitamin B12',
        'Vitamin B6',
        'Folate',
        'Magnesium',
      ],
      optional: const ['Vitamin B Complex', 'Magnesium'],
      note: 'أو تركيبة B-Complex + Magnesium',
      imageIndex: 4,
    ),
    _b(
      id: 'healthy_50',
      title: 'باقة كبار السن +50',
      icon: '🧓',
      supplements: const [
        'Multivitamin 50+',
        'Vitamin D3',
        'Vitamin B12',
      ],
      optional: const ['Calcium', 'Omega-3', 'Magnesium'],
      note: 'حسب الغذاء والحاجة',
      imageIndex: 0,
    ),
    _b(
      id: 'men_50',
      title: 'باقة الرجال +50',
      icon: '👔',
      supplements: const [
        'Men\'s Multivitamin 50+',
        'Vitamin D3',
        'Vitamin B12',
        'Omega-3',
      ],
      optional: const ['Magnesium'],
      imageIndex: 1,
    ),
    _b(
      id: 'women_50',
      title: 'باقة النساء +50',
      icon: '🌸',
      supplements: const ['Women\'s Multivitamin 50+', 'Vitamin D3'],
      optional: const ['Calcium', 'Vitamin B12', 'Magnesium', 'Omega-3'],
      note: 'حسب الحاجة',
      imageIndex: 2,
    ),
    _b(
      id: 'eye',
      title: 'باقة صحة العين',
      icon: '👁️',
      supplements: const ['Lutein', 'Zeaxanthin'],
      optional: const ['Zinc', 'Vitamin C', 'Vitamin E', 'Copper'],
      note: 'حسب التركيبة المعتمدة',
      imageIndex: 3,
    ),
    _b(
      id: 'iron',
      title: 'باقة الحديد',
      icon: '🩸',
      supplements: const ['Iron', 'Vitamin C'],
      optional: const ['Folic Acid', 'Vitamin B12'],
      note: 'تُصرف بعد تقييم الحاجة',
      imageIndex: 4,
    ),
    _b(
      id: 'vitamin_d',
      title: 'باقة فيتامين D',
      icon: '🌞',
      supplements: const ['Vitamin D3'],
      optional: const ['Calcium', 'Magnesium'],
      note: 'اختياري حسب الحاجة الغذائية',
      imageIndex: 0,
    ),
    _b(
      id: 'magnesium',
      title: 'باقة المغنيسيوم',
      icon: '🧂',
      supplements: const ['Magnesium'],
      optional: const [
        'Magnesium Citrate',
        'Magnesium Glycinate',
        'Magnesium Oxide',
      ],
      note: 'يختار الصيدلي الشكل المناسب',
      imageIndex: 1,
    ),
    _b(
      id: 'b_complex',
      title: 'باقة B-Complex',
      icon: '🅱️',
      supplements: const [
        'Vitamin B1',
        'Vitamin B2',
        'Vitamin B3',
        'Vitamin B5',
        'Vitamin B6',
        'Biotin (B7)',
        'Folate (B9)',
        'Vitamin B12',
      ],
      note: 'أو منتج B-Complex جاهز',
      imageIndex: 2,
    ),
    _b(
      id: 'omega3',
      title: 'باقة أوميغا 3',
      icon: '🐟',
      supplements: const ['Fish Oil / Omega-3', 'EPA', 'DHA'],
      imageIndex: 3,
    ),
    _b(
      id: 'pregnancy',
      title: 'باقة الحمل',
      icon: '🤰',
      supplements: const ['Folic Acid', 'Iron', 'Vitamin D', 'Iodine'],
      optional: const [
        'Vitamin B12',
        'Zinc',
        'Vitamin C',
        'B Vitamins',
        'Magnesium',
        'DHA',
      ],
      note: 'تحت إشراف الطبيب/الصيدلي',
      imageIndex: 4,
    ),
    _b(
      id: 'preconception',
      title: 'باقة التخطيط للحمل',
      icon: '🌱',
      supplements: const ['Folic Acid / Folate'],
      optional: const [
        'Vitamin D',
        'Vitamin B12',
        'Iodine',
        'Zinc',
        'Iron',
      ],
      note: 'قد تستخدم تركيبة Prenatal/Pre-Conception',
      imageIndex: 0,
    ),
    _b(
      id: 'breastfeeding',
      title: 'باقة الرضاعة',
      icon: '🍼',
      supplements: const [
        'Postnatal Multivitamin',
        'Vitamin D',
        'Iodine',
        'Omega-3 / DHA',
      ],
      note: 'حسب تقييم الطبيب/الصيدلي — الحديد وغيره حسب الحاجة',
      imageIndex: 1,
    ),
    _b(
      id: 'kids',
      title: 'باقة الأطفال اليومية',
      icon: '🧒',
      supplements: const ['Children\'s Multivitamin', 'Vitamin D'],
      optional: const ['Omega-3 / DHA'],
      note: 'حسب العمر وتقييم الطبيب/الصيدلي',
      imageIndex: 2,
    ),
    _b(
      id: 'teen',
      title: 'باقة المراهقين',
      icon: '🧑',
      supplements: const ['Multivitamin', 'Vitamin D'],
      optional: const ['Calcium', 'Iron', 'Omega-3'],
      note: 'حسب العمر والجنس والغذاء',
      imageIndex: 3,
    ),
    _b(
      id: 'vegan',
      title: 'باقة النباتيين',
      icon: '🥬',
      supplements: const ['Vitamin B12', 'Vitamin D', 'Iodine'],
      optional: const [
        'Iron',
        'Calcium',
        'Zinc',
        'Omega-3 من الطحالب (Algal DHA/EPA)',
      ],
      note: 'حسب النظام الغذائي',
      imageIndex: 4,
    ),
    _b(
      id: 'b12',
      title: 'باقة نقص B12',
      icon: '💊',
      supplements: const ['Vitamin B12'],
      optional: const ['Cyanocobalamin', 'Methylcobalamin'],
      note: 'يختار الصيدلي الشكل المناسب',
      imageIndex: 0,
    ),
    _b(
      id: 'calcium_d',
      title: 'باقة الكالسيوم وفيتامين D',
      icon: '🦴',
      supplements: const ['Calcium', 'Vitamin D3'],
      imageIndex: 1,
    ),
    _b(
      id: 'electrolytes',
      title: 'باقة الإلكتروليت',
      icon: '💧',
      supplements: const ['Sodium', 'Potassium', 'Magnesium', 'Chloride'],
      note: 'المكونات حسب المنتج',
      imageIndex: 2,
    ),
    _b(
      id: 'collagen',
      title: 'باقة الكولاجين',
      icon: '💎',
      supplements: const [
        'Hydrolyzed Collagen / Collagen Peptides',
        'Vitamin C',
      ],
      imageIndex: 3,
    ),
    _b(
      id: 'joints',
      title: 'باقة دعم المفاصل',
      icon: '🦵',
      supplements: const ['Glucosamine', 'Chondroitin'],
      optional: const ['MSM', 'Collagen'],
      imageIndex: 4,
    ),
  ];
}
